
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.values;

public interface CommentValues {
    String nameClicked();
    String contentClicked();
    Boolean isExperiment();
}
