
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.TextView;
import android.widget.LinearLayout;
import x7c1.linen.glue.res.view.CustomSwipeToRefresh;
import android.support.v4.widget.SwipeRefreshLayout;
import android.widget.ListView;

public class ActivityMain extends RecyclerView.ViewHolder {

    public final TextView sampleText;
    public final LinearLayout swipeContainer;
    public final x7c1.linen.glue.res.view.CustomSwipeToRefresh swipeLayoutLeft;
    public final android.support.v7.widget.RecyclerView sampleLeftList;
    public final android.support.v4.widget.SwipeRefreshLayout swipeLayoutCenter;
    public final android.support.v7.widget.RecyclerView sampleCenterList;
    public final android.support.v4.widget.SwipeRefreshLayout swipeLayoutRight;
    public final ListView sampleRightList;
    public final View dummySurface;

    public ActivityMain(
        View itemView,
        TextView sampleText,
        LinearLayout swipeContainer,
        x7c1.linen.glue.res.view.CustomSwipeToRefresh swipeLayoutLeft,
        android.support.v7.widget.RecyclerView sampleLeftList,
        android.support.v4.widget.SwipeRefreshLayout swipeLayoutCenter,
        android.support.v7.widget.RecyclerView sampleCenterList,
        android.support.v4.widget.SwipeRefreshLayout swipeLayoutRight,
        ListView sampleRightList,
        View dummySurface
    ){
        super(itemView);
        this.sampleText = sampleText;
        this.swipeContainer = swipeContainer;
        this.swipeLayoutLeft = swipeLayoutLeft;
        this.sampleLeftList = sampleLeftList;
        this.swipeLayoutCenter = swipeLayoutCenter;
        this.sampleCenterList = sampleCenterList;
        this.swipeLayoutRight = swipeLayoutRight;
        this.sampleRightList = sampleRightList;
        this.dummySurface = dummySurface;
    }
}
