
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.support.v7.widget.Toolbar;
import android.widget.Button;
import android.widget.TextView;

public class DevCreateRecordsLayout extends RecyclerView.ViewHolder {

    public final android.support.v7.widget.Toolbar toolbar;
    public final Button selectChannels;
    public final TextView selectedChannels;
    public final Button createDummySources;
    public final Button createDummies;
    public final Button createPreset;
    public final Button createPresetJp;
    public final Button createPresetEn;
    public final Button markAllAsUnread;
    public final Button deleteDatabase;

    public DevCreateRecordsLayout(
        View itemView,
        android.support.v7.widget.Toolbar toolbar,
        Button selectChannels,
        TextView selectedChannels,
        Button createDummySources,
        Button createDummies,
        Button createPreset,
        Button createPresetJp,
        Button createPresetEn,
        Button markAllAsUnread,
        Button deleteDatabase
    ){
        super(itemView);
        this.toolbar = toolbar;
        this.selectChannels = selectChannels;
        this.selectedChannels = selectedChannels;
        this.createDummySources = createDummySources;
        this.createDummies = createDummies;
        this.createPreset = createPreset;
        this.createPresetJp = createPresetJp;
        this.createPresetEn = createPresetEn;
        this.markAllAsUnread = markAllAsUnread;
        this.deleteDatabase = deleteDatabase;
    }
}
