
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.support.v7.widget.Toolbar;
import android.widget.Button;

public class DevCreateDummiesLayout extends RecyclerView.ViewHolder {

    public final android.support.v7.widget.Toolbar toolbar;
    public final Button createDummies;
    public final Button deleteDatabase;

    public DevCreateDummiesLayout(
        View itemView,
        android.support.v7.widget.Toolbar toolbar,
        Button createDummies,
        Button deleteDatabase
    ){
        super(itemView);
        this.toolbar = toolbar;
        this.createDummies = createDummies;
        this.deleteDatabase = deleteDatabase;
    }
}
