
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class InspectorRowSourceItem extends InspectorRow {

    public final TextView body;

    public InspectorRowSourceItem(
        View itemView,
        TextView body
    ){
        super(itemView);
        this.body = body;
    }
}
