
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.support.v7.widget.Toolbar;
import android.support.v4.widget.SwipeRefreshLayout;
import android.widget.ListView;
import android.widget.TextView;

public class MainLayout extends RecyclerView.ViewHolder {

    public final LinearLayout menuArea;
    public final LinearLayout swipeContainer;
    public final RelativeLayout swipeLayoutLeft;
    public final android.support.v7.widget.Toolbar sourceToolbar;
    public final android.support.v7.widget.RecyclerView sampleLeftList;
    public final android.support.v4.widget.SwipeRefreshLayout swipeLayoutCenter;
    public final android.support.v7.widget.RecyclerView sampleCenterList;
    public final android.support.v4.widget.SwipeRefreshLayout swipeLayoutRight;
    public final ListView sampleRightList;
    public final TextView sampleText;
    public final View dummySurface;

    public MainLayout(
        View itemView,
        LinearLayout menuArea,
        LinearLayout swipeContainer,
        RelativeLayout swipeLayoutLeft,
        android.support.v7.widget.Toolbar sourceToolbar,
        android.support.v7.widget.RecyclerView sampleLeftList,
        android.support.v4.widget.SwipeRefreshLayout swipeLayoutCenter,
        android.support.v7.widget.RecyclerView sampleCenterList,
        android.support.v4.widget.SwipeRefreshLayout swipeLayoutRight,
        ListView sampleRightList,
        TextView sampleText,
        View dummySurface
    ){
        super(itemView);
        this.menuArea = menuArea;
        this.swipeContainer = swipeContainer;
        this.swipeLayoutLeft = swipeLayoutLeft;
        this.sourceToolbar = sourceToolbar;
        this.sampleLeftList = sampleLeftList;
        this.swipeLayoutCenter = swipeLayoutCenter;
        this.sampleCenterList = sampleCenterList;
        this.swipeLayoutRight = swipeLayoutRight;
        this.sampleRightList = sampleRightList;
        this.sampleText = sampleText;
        this.dummySurface = dummySurface;
    }
}
