
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.LinearLayout;
import android.support.design.widget.CoordinatorLayout;
import android.support.v7.widget.Toolbar;
import android.widget.TextView;

public class MainLayout extends RecyclerView.ViewHolder {

    public final LinearLayout menuArea;
    public final LinearLayout paneContainer;
    public final android.support.design.widget.CoordinatorLayout sourceArea;
    public final android.support.v7.widget.Toolbar sourceToolbar;
    public final android.support.v7.widget.RecyclerView sourceList;
    public final LinearLayout entryArea;
    public final android.support.v7.widget.Toolbar entryToolbar;
    public final android.support.v7.widget.RecyclerView entryList;
    public final LinearLayout entryDetailArea;
    public final android.support.v7.widget.Toolbar entryDetailToolbar;
    public final android.support.v7.widget.RecyclerView entryDetailList;
    public final TextView sampleText;
    public final View dummySurface;

    public MainLayout(
        View itemView,
        LinearLayout menuArea,
        LinearLayout paneContainer,
        android.support.design.widget.CoordinatorLayout sourceArea,
        android.support.v7.widget.Toolbar sourceToolbar,
        android.support.v7.widget.RecyclerView sourceList,
        LinearLayout entryArea,
        android.support.v7.widget.Toolbar entryToolbar,
        android.support.v7.widget.RecyclerView entryList,
        LinearLayout entryDetailArea,
        android.support.v7.widget.Toolbar entryDetailToolbar,
        android.support.v7.widget.RecyclerView entryDetailList,
        TextView sampleText,
        View dummySurface
    ){
        super(itemView);
        this.menuArea = menuArea;
        this.paneContainer = paneContainer;
        this.sourceArea = sourceArea;
        this.sourceToolbar = sourceToolbar;
        this.sourceList = sourceList;
        this.entryArea = entryArea;
        this.entryToolbar = entryToolbar;
        this.entryList = entryList;
        this.entryDetailArea = entryDetailArea;
        this.entryDetailToolbar = entryDetailToolbar;
        this.entryDetailList = entryDetailList;
        this.sampleText = sampleText;
        this.dummySurface = dummySurface;
    }
}
