
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.Button;
import android.support.design.widget.CoordinatorLayout;
import android.support.v7.widget.Toolbar;
import android.support.design.widget.FloatingActionButton;
import android.widget.RelativeLayout;

public class MainLayout extends RecyclerView.ViewHolder {

    public final LinearLayout menuArea;
    public final Button createDummies;
    public final Button initDummies;
    public final LinearLayout paneContainer;
    public final android.support.design.widget.CoordinatorLayout sourceArea;
    public final android.support.v7.widget.Toolbar sourceToolbar;
    public final android.support.v7.widget.RecyclerView sourceList;
    public final android.support.design.widget.FloatingActionButton sourceToNext;
    public final RelativeLayout entryArea;
    public final android.support.v7.widget.Toolbar entryToolbar;
    public final android.support.v7.widget.RecyclerView entryList;
    public final android.support.design.widget.FloatingActionButton entryToNext;
    public final LinearLayout entryDetailArea;
    public final android.support.v7.widget.Toolbar entryDetailToolbar;
    public final android.support.v7.widget.RecyclerView entryDetailList;
    public final View dummySurface;

    public MainLayout(
        View itemView,
        LinearLayout menuArea,
        Button createDummies,
        Button initDummies,
        LinearLayout paneContainer,
        android.support.design.widget.CoordinatorLayout sourceArea,
        android.support.v7.widget.Toolbar sourceToolbar,
        android.support.v7.widget.RecyclerView sourceList,
        android.support.design.widget.FloatingActionButton sourceToNext,
        RelativeLayout entryArea,
        android.support.v7.widget.Toolbar entryToolbar,
        android.support.v7.widget.RecyclerView entryList,
        android.support.design.widget.FloatingActionButton entryToNext,
        LinearLayout entryDetailArea,
        android.support.v7.widget.Toolbar entryDetailToolbar,
        android.support.v7.widget.RecyclerView entryDetailList,
        View dummySurface
    ){
        super(itemView);
        this.menuArea = menuArea;
        this.createDummies = createDummies;
        this.initDummies = initDummies;
        this.paneContainer = paneContainer;
        this.sourceArea = sourceArea;
        this.sourceToolbar = sourceToolbar;
        this.sourceList = sourceList;
        this.sourceToNext = sourceToNext;
        this.entryArea = entryArea;
        this.entryToolbar = entryToolbar;
        this.entryList = entryList;
        this.entryToNext = entryToNext;
        this.entryDetailArea = entryDetailArea;
        this.entryDetailToolbar = entryDetailToolbar;
        this.entryDetailList = entryDetailList;
        this.dummySurface = dummySurface;
    }
}
