
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class MenuRowItem extends MenuRow {

    public final TextView text;

    public MenuRowItem(
        View itemView,
        TextView text
    ){
        super(itemView);
        this.text = text;
    }
}
