
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;

public class SettingChannelsLayout extends RecyclerView.ViewHolder {

    public final android.support.v7.widget.RecyclerView channelList;

    public SettingChannelsLayout(
        View itemView,
        android.support.v7.widget.RecyclerView channelList
    ){
        super(itemView);
        this.channelList = channelList;
    }
}
