
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;

public class SettingSourceCopy extends RecyclerView.ViewHolder {

    public final android.support.v7.widget.RecyclerView channels;

    public SettingSourceCopy(
        View itemView,
        android.support.v7.widget.RecyclerView channels
    ){
        super(itemView);
        this.channels = channels;
    }
}
