
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.support.v7.widget.Toolbar;

public class SettingUpdaterLayout extends RecyclerView.ViewHolder {

    public final android.support.v7.widget.Toolbar toolbar;
    public final android.support.v7.widget.RecyclerView schedules;

    public SettingUpdaterLayout(
        View itemView,
        android.support.v7.widget.Toolbar toolbar,
        android.support.v7.widget.RecyclerView schedules
    ){
        super(itemView);
        this.toolbar = toolbar;
        this.schedules = schedules;
    }
}
