
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.CheckBox;
import android.widget.TextView;

public class SettingSourceAttachRowItem extends SettingSourceAttachRow {

    public final CheckBox checked;
    public final TextView label;

    public SettingSourceAttachRowItem(
        View itemView,
        CheckBox checked,
        TextView label
    ){
        super(itemView);
        this.checked = checked;
        this.label = label;
    }
}
