
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.TextView;
import android.widget.ImageButton;
import android.support.v7.widget.SwitchCompat;
import android.widget.SeekBar;

public class SettingChannelSourcesRow extends RecyclerView.ViewHolder {

    public final TextView title;
    public final ImageButton menu;
    public final TextView description;
    public final android.support.v7.widget.SwitchCompat switchSubscribe;
    public final SeekBar ratingBar;
    public final TextView ratingValue;
    public final TextView ratingLabel;

    public SettingChannelSourcesRow(
        View itemView,
        TextView title,
        ImageButton menu,
        TextView description,
        android.support.v7.widget.SwitchCompat switchSubscribe,
        SeekBar ratingBar,
        TextView ratingValue,
        TextView ratingLabel
    ){
        super(itemView);
        this.title = title;
        this.menu = menu;
        this.description = description;
        this.switchSubscribe = switchSubscribe;
        this.ratingBar = ratingBar;
        this.ratingValue = ratingValue;
        this.ratingLabel = ratingLabel;
    }
}
