
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;

public class SettingMyChannelRowFooter extends SettingMyChannelRow {

    

    public SettingMyChannelRowFooter(
        View itemView
    ){
        super(itemView);
        
    }
}
