
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.support.design.widget.TextInputLayout;
import android.support.v7.widget.AppCompatEditText;

public class SettingMyChannelCreate extends RecyclerView.ViewHolder {

    public final android.support.design.widget.TextInputLayout channelNameLayout;
    public final android.support.v7.widget.AppCompatEditText channelName;
    public final android.support.design.widget.TextInputLayout channelDescriptionLayout;
    public final android.support.v7.widget.AppCompatEditText channelDescription;

    public SettingMyChannelCreate(
        View itemView,
        android.support.design.widget.TextInputLayout channelNameLayout,
        android.support.v7.widget.AppCompatEditText channelName,
        android.support.design.widget.TextInputLayout channelDescriptionLayout,
        android.support.v7.widget.AppCompatEditText channelDescription
    ){
        super(itemView);
        this.channelNameLayout = channelNameLayout;
        this.channelName = channelName;
        this.channelDescriptionLayout = channelDescriptionLayout;
        this.channelDescription = channelDescription;
    }
}
