
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

public class SettingChannelOrderRowItem extends SettingChannelOrderRow {

    public final ImageView startDraggingLeft;
    public final ImageView startDraggingRight;
    public final TextView name;

    public SettingChannelOrderRowItem(
        View itemView,
        ImageView startDraggingLeft,
        ImageView startDraggingRight,
        TextView name
    ){
        super(itemView);
        this.startDraggingLeft = startDraggingLeft;
        this.startDraggingRight = startDraggingRight;
        this.name = name;
    }
}
