
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class SettingChannelOrderRowItem extends SettingChannelOrderRow {

    public final TextView name;

    public SettingChannelOrderRowItem(
        View itemView,
        TextView name
    ){
        super(itemView);
        this.name = name;
    }
}
