
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class SourceSearchRowSourceNotFound extends SourceSearchRow {

    public final TextView title;
    public final TextView url;
    public final TextView open;

    public SourceSearchRowSourceNotFound(
        View itemView,
        TextView title,
        TextView url,
        TextView open
    ){
        super(itemView);
        this.title = title;
        this.url = url;
        this.open = open;
    }
}
