
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.support.design.widget.TextInputLayout;
import android.support.v7.widget.AppCompatEditText;

public class SourceSearchStart extends RecyclerView.ViewHolder {

    public final android.support.design.widget.TextInputLayout originUrlLayout;
    public final android.support.v7.widget.AppCompatEditText originUrl;

    public SourceSearchStart(
        View itemView,
        android.support.design.widget.TextInputLayout originUrlLayout,
        android.support.v7.widget.AppCompatEditText originUrl
    ){
        super(itemView);
        this.originUrlLayout = originUrlLayout;
        this.originUrl = originUrl;
    }
}
