
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class SourceSearchRowLoadingErrorItem extends SourceSearchRow {

    public final TextView url;
    public final TextView message;
    public final TextView open;

    public SourceSearchRowLoadingErrorItem(
        View itemView,
        TextView url,
        TextView message,
        TextView open
    ){
        super(itemView);
        this.url = url;
        this.message = message;
        this.open = open;
    }
}
