
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class SourceSearchRowClientError extends SourceSearchRow {

    public final TextView message;
    public final TextView url;
    public final TextView retry;

    public SourceSearchRowClientError(
        View itemView,
        TextView message,
        TextView url,
        TextView retry
    ){
        super(itemView);
        this.message = message;
        this.url = url;
        this.retry = retry;
    }
}
