
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class SourceSearchRowSourceItem extends SourceSearchRow {

    public final TextView title;
    public final TextView description;
    public final TextView subscribe;
    public final TextView entries;

    public SourceSearchRowSourceItem(
        View itemView,
        TextView title,
        TextView description,
        TextView subscribe,
        TextView entries
    ){
        super(itemView);
        this.title = title;
        this.description = description;
        this.subscribe = subscribe;
        this.entries = entries;
    }
}
