
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class SourceSearchRowLoadingErrorLabel extends SourceSearchRow {

    public final TextView message;
    public final TextView date;

    public SourceSearchRowLoadingErrorLabel(
        View itemView,
        TextView message,
        TextView date
    ){
        super(itemView);
        this.message = message;
        this.date = date;
    }
}
