
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.TextView;

public class SourceRow extends RecyclerView.ViewHolder {

    public final TextView title;
    public final TextView description;
    public final View stateUnloaded;
    public final View statePrefetched;

    public SourceRow(
        View itemView,
        TextView title,
        TextView description,
        View stateUnloaded,
        View statePrefetched
    ){
        super(itemView);
        this.title = title;
        this.description = description;
        this.stateUnloaded = stateUnloaded;
        this.statePrefetched = statePrefetched;
    }
}
