
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.CheckBox;
import android.widget.TextView;

public class SubscribeSourceRowItem extends SubscribeSourceRow {

    public final CheckBox checkbox;
    public final TextView label;

    public SubscribeSourceRowItem(
        View itemView,
        CheckBox checkbox,
        TextView label
    ){
        super(itemView);
        this.checkbox = checkbox;
        this.label = label;
    }
}
