
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class UnreadOutlineRowEntry extends UnreadOutlineRow {

    public final TextView title;

    public UnreadOutlineRowEntry(
        View itemView,
        TextView title
    ){
        super(itemView);
        this.title = title;
    }
}
