
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class UnreadDetailRowEntry extends UnreadDetailRow {

    public final TextView title;
    public final TextView content;
    public final TextView later;
    public final TextView visit;

    public UnreadDetailRowEntry(
        View itemView,
        TextView title,
        TextView content,
        TextView later,
        TextView visit
    ){
        super(itemView);
        this.title = title;
        this.content = content;
        this.later = later;
        this.visit = visit;
    }
}
