
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.support.v7.widget.Toolbar;
import android.support.design.widget.FloatingActionButton;

public class UnreadItemsPanes extends RecyclerView.ViewHolder {

    public final LinearLayout paneContainer;
    public final RelativeLayout sourceArea;
    public final android.support.v7.widget.Toolbar sourceToolbar;
    public final android.support.v7.widget.RecyclerView sourceList;
    public final android.support.v7.widget.Toolbar sourceBottomBar;
    public final android.support.design.widget.FloatingActionButton sourceToNext;
    public final RelativeLayout entryArea;
    public final android.support.v7.widget.Toolbar entryToolbar;
    public final android.support.v7.widget.RecyclerView entryList;
    public final android.support.v7.widget.Toolbar entryBottomBar;
    public final android.support.design.widget.FloatingActionButton entryToNext;
    public final RelativeLayout entryDetailArea;
    public final android.support.v7.widget.Toolbar entryDetailToolbar;
    public final android.support.v7.widget.RecyclerView entryDetailList;
    public final android.support.v7.widget.Toolbar detailBottomBar;
    public final android.support.design.widget.FloatingActionButton detailToNext;

    public UnreadItemsPanes(
        View itemView,
        LinearLayout paneContainer,
        RelativeLayout sourceArea,
        android.support.v7.widget.Toolbar sourceToolbar,
        android.support.v7.widget.RecyclerView sourceList,
        android.support.v7.widget.Toolbar sourceBottomBar,
        android.support.design.widget.FloatingActionButton sourceToNext,
        RelativeLayout entryArea,
        android.support.v7.widget.Toolbar entryToolbar,
        android.support.v7.widget.RecyclerView entryList,
        android.support.v7.widget.Toolbar entryBottomBar,
        android.support.design.widget.FloatingActionButton entryToNext,
        RelativeLayout entryDetailArea,
        android.support.v7.widget.Toolbar entryDetailToolbar,
        android.support.v7.widget.RecyclerView entryDetailList,
        android.support.v7.widget.Toolbar detailBottomBar,
        android.support.design.widget.FloatingActionButton detailToNext
    ){
        super(itemView);
        this.paneContainer = paneContainer;
        this.sourceArea = sourceArea;
        this.sourceToolbar = sourceToolbar;
        this.sourceList = sourceList;
        this.sourceBottomBar = sourceBottomBar;
        this.sourceToNext = sourceToNext;
        this.entryArea = entryArea;
        this.entryToolbar = entryToolbar;
        this.entryList = entryList;
        this.entryBottomBar = entryBottomBar;
        this.entryToNext = entryToNext;
        this.entryDetailArea = entryDetailArea;
        this.entryDetailToolbar = entryDetailToolbar;
        this.entryDetailList = entryDetailList;
        this.detailBottomBar = detailBottomBar;
        this.detailToNext = detailToNext;
    }
}
