
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.view.View;
import android.widget.ProgressBar;

public class UnreadOutlineRowFooter extends UnreadOutlineRow {

    public final ProgressBar progressBar;

    public UnreadOutlineRowFooter(
        View itemView,
        ProgressBar progressBar
    ){
        super(itemView);
        this.progressBar = progressBar;
    }
}
