
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;

public class UnreadDetailRow extends RecyclerView.ViewHolder {
    public UnreadDetailRow(View itemView) {
        super(itemView);
    }
}
