
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.values;

import android.content.Context;
import x7c1.wheat.ancient.resource.ValuesProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.values.CommentValues;

public class CommentValuesProvider implements ValuesProvider<CommentValues> {
    private final CommentValues comment;

    public CommentValuesProvider(Context context){
        comment = new CommentValuesImpl(
            context,
            R.string.comment__name_clicked,
            R.string.comment__content_clicked,
            R.bool.comment__is_experiment
        );
    }

    @Override
    public CommentValues get(){
        return comment;
    }

    private static class CommentValuesImpl implements CommentValues {
        private final Context context;
        private final int nameClickedId;
        private final int contentClickedId;
        private final int isExperimentId;
        private String nameClicked;
        private String contentClicked;
        private Boolean isExperiment;

        CommentValuesImpl(
            Context context,
            int nameClicked,
            int contentClicked,
            int isExperiment
        ){
            this.context = context;
            this.nameClickedId = nameClicked;
            this.contentClickedId = contentClicked;
            this.isExperimentId = isExperiment;
        }

        @Override
        public String nameClicked(){
            if (nameClicked == null){
                nameClicked = context.getResources().getString(nameClickedId);
            }
            return nameClicked;
        }
        @Override
        public String contentClicked(){
            if (contentClicked == null){
                contentClicked = context.getResources().getString(contentClickedId);
            }
            return contentClicked;
        }
        @Override
        public Boolean isExperiment(){
            if (isExperiment == null){
                isExperiment = context.getResources().getBoolean(isExperimentId);
            }
            return isExperiment;
        }
    }
}
