
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.v7.widget.Toolbar;
import android.widget.Button;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.DevCreateDummiesLayout;

public class DevCreateDummiesLayoutProvider implements ViewHolderProvider<DevCreateDummiesLayout> {

    private final LayoutInflater inflater;

    public DevCreateDummiesLayoutProvider(Context context){
        inflater = LayoutInflater.from(context);
    }

    @Override
    public int layoutId(){
        return R.layout.dev_create_dummies_layout;
    }

    @Override
    public DevCreateDummiesLayout inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public DevCreateDummiesLayout inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.dev_create_dummies_layout, parent, attachToRoot);
        return new DevCreateDummiesLayout(
            view,
            (android.support.v7.widget.Toolbar) view.findViewById(R.id.dev_create_dummies_layout__toolbar),
            (Button) view.findViewById(R.id.dev_create_dummies_layout__create_dummies),
            (Button) view.findViewById(R.id.dev_create_dummies_layout__delete_database)
        );
    }
}
