
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.InspectorRowSourceItem;

public class InspectorRowSourceItemProvider implements ViewHolderProvider<InspectorRowSourceItem> {

    private final LayoutInflater inflater;

    public InspectorRowSourceItemProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public InspectorRowSourceItemProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.inspector_row__source_item;
    }

    @Override
    public InspectorRowSourceItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public InspectorRowSourceItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.inspector_row__source_item, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<InspectorRowSourceItem> factory(){
        return new ViewHolderProviderFactory<InspectorRowSourceItem>() {
            @Override
            public ViewHolderProvider<InspectorRowSourceItem> create(LayoutInflater inflater){
                return new InspectorRowSourceItemProvider(inflater);
            }
            @Override
            public ViewHolderProvider<InspectorRowSourceItem> create(Context context){
                return new InspectorRowSourceItemProvider(context);
            }
            @Override
            public InspectorRowSourceItem createViewHolder(View view){
                return new InspectorRowSourceItem(
                    view,
                    (TextView) view.findViewById(R.id.inspector_row__source_item__body)
                );
            }
        };
    }
}
