
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.InspectorRowSourceLabel;

public class InspectorRowSourceLabelProvider implements ViewHolderProvider<InspectorRowSourceLabel> {

    private final LayoutInflater inflater;

    public InspectorRowSourceLabelProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public InspectorRowSourceLabelProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.inspector_row__source_label;
    }

    @Override
    public InspectorRowSourceLabel inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public InspectorRowSourceLabel inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.inspector_row__source_label, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<InspectorRowSourceLabel> factory(){
        return new ViewHolderProviderFactory<InspectorRowSourceLabel>() {
            @Override
            public ViewHolderProvider<InspectorRowSourceLabel> create(LayoutInflater inflater){
                return new InspectorRowSourceLabelProvider(inflater);
            }
            @Override
            public ViewHolderProvider<InspectorRowSourceLabel> create(Context context){
                return new InspectorRowSourceLabelProvider(context);
            }
            @Override
            public InspectorRowSourceLabel createViewHolder(View view){
                return new InspectorRowSourceLabel(
                    view,
                    (TextView) view.findViewById(R.id.inspector_row__source_label__body)
                );
            }
        };
    }
}
