
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.v7.widget.Toolbar;
import android.support.v7.widget.RecyclerView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.InspectorLayout;

public class InspectorLayoutProvider implements ViewHolderProvider<InspectorLayout> {

    private final LayoutInflater inflater;

    public InspectorLayoutProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public InspectorLayoutProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.inspector_layout;
    }

    @Override
    public InspectorLayout inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public InspectorLayout inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.inspector_layout, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<InspectorLayout> factory(){
        return new ViewHolderProviderFactory<InspectorLayout>() {
            @Override
            public ViewHolderProvider<InspectorLayout> create(LayoutInflater inflater){
                return new InspectorLayoutProvider(inflater);
            }
            @Override
            public ViewHolderProvider<InspectorLayout> create(Context context){
                return new InspectorLayoutProvider(context);
            }
            @Override
            public InspectorLayout createViewHolder(View view){
                return new InspectorLayout(
                    view,
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.inspector_layout__toolbar),
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.inspector_layout__reports)
                );
            }
        };
    }
}
