
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.Button;
import android.widget.RelativeLayout;
import android.support.v7.widget.Toolbar;
import android.support.v7.widget.RecyclerView;
import android.support.design.widget.FloatingActionButton;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.MainLayout;

public class MainLayoutProvider implements ViewHolderProvider<MainLayout> {

    private final LayoutInflater inflater;

    public MainLayoutProvider(Context context){
        inflater = LayoutInflater.from(context);
    }

    @Override
    public MainLayout inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public MainLayout inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.main_layout, parent, attachToRoot);
        return new MainLayout(
            view,
            (LinearLayout) view.findViewById(R.id.main_layout__menu_area),
            (Button) view.findViewById(R.id.main_layout__create_dummies),
            (Button) view.findViewById(R.id.main_layout__init_dummies),
            (LinearLayout) view.findViewById(R.id.activity_main__pane_container),
            (RelativeLayout) view.findViewById(R.id.activity_main__source_area),
            (android.support.v7.widget.Toolbar) view.findViewById(R.id.activity_main__source_toolbar),
            (android.support.v7.widget.RecyclerView) view.findViewById(R.id.activity_main__source_list),
            (android.support.design.widget.FloatingActionButton) view.findViewById(R.id.activity_main__source_to_next),
            (RelativeLayout) view.findViewById(R.id.activity_main__entry_area),
            (android.support.v7.widget.Toolbar) view.findViewById(R.id.activity_main__entry_toolbar),
            (android.support.v7.widget.RecyclerView) view.findViewById(R.id.activity_main__entry_list),
            (android.support.design.widget.FloatingActionButton) view.findViewById(R.id.activity_main__entry_to_next),
            (LinearLayout) view.findViewById(R.id.activity_main__entry_detail_area),
            (android.support.v7.widget.Toolbar) view.findViewById(R.id.activity_main__entry_detail_toolbar),
            (android.support.v7.widget.RecyclerView) view.findViewById(R.id.activity_main__entry_detail_list),
            (View) view.findViewById(R.id.activity_main__dummy_surface)
        );
    }
}
