
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.MenuRowSeparator;

public class MenuRowSeparatorProvider implements ViewHolderProvider<MenuRowSeparator> {

    private final LayoutInflater inflater;

    public MenuRowSeparatorProvider(Context context){
        inflater = LayoutInflater.from(context);
    }

    @Override
    public int layoutId(){
        return R.layout.menu_row__separator;
    }

    @Override
    public MenuRowSeparator inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public MenuRowSeparator inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.menu_row__separator, parent, attachToRoot);
        return new MenuRowSeparator(
            view
        );
    }
}
