
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.MenuRowSeparator;

public class MenuRowSeparatorProvider implements ViewHolderProvider<MenuRowSeparator> {

    private final LayoutInflater inflater;

    public MenuRowSeparatorProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public MenuRowSeparatorProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.menu_row__separator;
    }

    @Override
    public MenuRowSeparator inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public MenuRowSeparator inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.menu_row__separator, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public MenuRowSeparator inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<MenuRowSeparator> factory(){
        return new ViewHolderProviderFactory<MenuRowSeparator>() {
            @Override
            public ViewHolderProvider<MenuRowSeparator> create(LayoutInflater inflater){
                return new MenuRowSeparatorProvider(inflater);
            }
            @Override
            public ViewHolderProvider<MenuRowSeparator> create(Context context){
                return new MenuRowSeparatorProvider(context);
            }
            @Override
            public MenuRowSeparator createViewHolder(View view){
                return new MenuRowSeparator(
                    view
                );
            }
        };
    }
}
