
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.MenuRowItem;

public class MenuRowItemProvider implements ViewHolderProvider<MenuRowItem> {

    private final LayoutInflater inflater;

    public MenuRowItemProvider(Context context){
        inflater = LayoutInflater.from(context);
    }

    @Override
    public MenuRowItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public MenuRowItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.menu_row__item, parent, attachToRoot);
        return new MenuRowItem(
            view,
            (TextView) view.findViewById(R.id.menu_row__item__text)
        );
    }
}
