
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.v7.widget.RecyclerView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingSourceCopy;

public class SettingSourceCopyProvider implements ViewHolderProvider<SettingSourceCopy> {

    private final LayoutInflater inflater;

    public SettingSourceCopyProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingSourceCopyProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_source_copy;
    }

    @Override
    public SettingSourceCopy inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingSourceCopy inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_source_copy, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingSourceCopy> factory(){
        return new ViewHolderProviderFactory<SettingSourceCopy>() {
            @Override
            public ViewHolderProvider<SettingSourceCopy> create(LayoutInflater inflater){
                return new SettingSourceCopyProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingSourceCopy> create(Context context){
                return new SettingSourceCopyProvider(context);
            }
            @Override
            public SettingSourceCopy createViewHolder(View view){
                return new SettingSourceCopy(
                    view,
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.setting_source_copy__channels)
                );
            }
        };
    }
}
