
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import android.widget.ImageButton;
import android.support.v7.widget.SwitchCompat;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingMyChannelRowItem;

public class SettingMyChannelRowItemProvider implements ViewHolderProvider<SettingMyChannelRowItem> {

    private final LayoutInflater inflater;

    public SettingMyChannelRowItemProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingMyChannelRowItemProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_my_channel_row__item;
    }

    @Override
    public SettingMyChannelRowItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingMyChannelRowItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_my_channel_row__item, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingMyChannelRowItem> factory(){
        return new ViewHolderProviderFactory<SettingMyChannelRowItem>() {
            @Override
            public ViewHolderProvider<SettingMyChannelRowItem> create(LayoutInflater inflater){
                return new SettingMyChannelRowItemProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingMyChannelRowItem> create(Context context){
                return new SettingMyChannelRowItemProvider(context);
            }
            @Override
            public SettingMyChannelRowItem createViewHolder(View view){
                return new SettingMyChannelRowItem(
                    view,
                    (TextView) view.findViewById(R.id.setting_my_channel_row__item__name),
                    (ImageButton) view.findViewById(R.id.setting_my_channel_row__item__menu),
                    (TextView) view.findViewById(R.id.setting_my_channel_row__item__description),
                    (android.support.v7.widget.SwitchCompat) view.findViewById(R.id.setting_my_channel_row__item__switch_subscribe),
                    (TextView) view.findViewById(R.id.setting_my_channel_row__item__edit),
                    (TextView) view.findViewById(R.id.setting_my_channel_row__item__sources)
                );
            }
        };
    }
}
