
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import android.support.v7.widget.SwitchCompat;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingChannelsRow;

public class SettingChannelsRowProvider implements ViewHolderProvider<SettingChannelsRow> {

    private final LayoutInflater inflater;

    public SettingChannelsRowProvider(Context context){
        inflater = LayoutInflater.from(context);
    }

    @Override
    public int layoutId(){
        return R.layout.setting_channels_row;
    }

    @Override
    public SettingChannelsRow inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingChannelsRow inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_channels_row, parent, attachToRoot);
        return new SettingChannelsRow(
            view,
            (TextView) view.findViewById(R.id.setting_channels_row__name),
            (TextView) view.findViewById(R.id.setting_channels_row__description),
            (android.support.v7.widget.SwitchCompat) view.findViewById(R.id.setting_channels_row__switch_subscribe),
            (TextView) view.findViewById(R.id.setting_channels_row__edit),
            (TextView) view.findViewById(R.id.setting_channels_row__sources)
        );
    }
}
