
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.v7.widget.Toolbar;
import android.widget.Button;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingUpdaterLayout;

public class SettingUpdaterLayoutProvider implements ViewHolderProvider<SettingUpdaterLayout> {

    private final LayoutInflater inflater;

    public SettingUpdaterLayoutProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingUpdaterLayoutProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_updater_layout;
    }

    @Override
    public SettingUpdaterLayout inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingUpdaterLayout inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_updater_layout, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingUpdaterLayout> factory(){
        return new ViewHolderProviderFactory<SettingUpdaterLayout>() {
            @Override
            public ViewHolderProvider<SettingUpdaterLayout> create(LayoutInflater inflater){
                return new SettingUpdaterLayoutProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingUpdaterLayout> create(Context context){
                return new SettingUpdaterLayoutProvider(context);
            }
            @Override
            public SettingUpdaterLayout createViewHolder(View view){
                return new SettingUpdaterLayout(
                    view,
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.setting_updater_layout__toolbar),
                    (Button) view.findViewById(R.id.setting_updater_layout__update_channels)
                );
            }
        };
    }
}
