
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import android.widget.ImageButton;
import android.support.v7.widget.SwitchCompat;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingPresetChannelRow;

public class SettingPresetChannelRowProvider implements ViewHolderProvider<SettingPresetChannelRow> {

    private final LayoutInflater inflater;

    public SettingPresetChannelRowProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingPresetChannelRowProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_preset_channel_row;
    }

    @Override
    public SettingPresetChannelRow inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingPresetChannelRow inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_preset_channel_row, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public SettingPresetChannelRow inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<SettingPresetChannelRow> factory(){
        return new ViewHolderProviderFactory<SettingPresetChannelRow>() {
            @Override
            public ViewHolderProvider<SettingPresetChannelRow> create(LayoutInflater inflater){
                return new SettingPresetChannelRowProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingPresetChannelRow> create(Context context){
                return new SettingPresetChannelRowProvider(context);
            }
            @Override
            public SettingPresetChannelRow createViewHolder(View view){
                return new SettingPresetChannelRow(
                    view,
                    (TextView) view.findViewById(R.id.setting_preset_channel_row__name),
                    (ImageButton) view.findViewById(R.id.setting_preset_channel_row__menu),
                    (TextView) view.findViewById(R.id.setting_preset_channel_row__description),
                    (android.support.v7.widget.SwitchCompat) view.findViewById(R.id.setting_preset_channel_row__switch_subscribe),
                    (TextView) view.findViewById(R.id.setting_preset_channel_row__sources)
                );
            }
        };
    }
}
