
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingScheduleTimeRowItem;

public class SettingScheduleTimeRowItemProvider implements ViewHolderProvider<SettingScheduleTimeRowItem> {

    private final LayoutInflater inflater;

    public SettingScheduleTimeRowItemProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingScheduleTimeRowItemProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_schedule_time_row__item;
    }

    @Override
    public SettingScheduleTimeRowItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingScheduleTimeRowItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_schedule_time_row__item, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingScheduleTimeRowItem> factory(){
        return new ViewHolderProviderFactory<SettingScheduleTimeRowItem>() {
            @Override
            public ViewHolderProvider<SettingScheduleTimeRowItem> create(LayoutInflater inflater){
                return new SettingScheduleTimeRowItemProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingScheduleTimeRowItem> create(Context context){
                return new SettingScheduleTimeRowItemProvider(context);
            }
            @Override
            public SettingScheduleTimeRowItem createViewHolder(View view){
                return new SettingScheduleTimeRowItem(
                    view,
                    (TextView) view.findViewById(R.id.setting_schedule_time_row__item__range)
                );
            }
        };
    }
}
