
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.design.widget.TextInputLayout;
import android.support.v7.widget.AppCompatEditText;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingMyChannelCreate;

public class SettingMyChannelCreateProvider implements ViewHolderProvider<SettingMyChannelCreate> {

    private final LayoutInflater inflater;

    public SettingMyChannelCreateProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingMyChannelCreateProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_my_channel_create;
    }

    @Override
    public SettingMyChannelCreate inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingMyChannelCreate inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_my_channel_create, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public SettingMyChannelCreate inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<SettingMyChannelCreate> factory(){
        return new ViewHolderProviderFactory<SettingMyChannelCreate>() {
            @Override
            public ViewHolderProvider<SettingMyChannelCreate> create(LayoutInflater inflater){
                return new SettingMyChannelCreateProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingMyChannelCreate> create(Context context){
                return new SettingMyChannelCreateProvider(context);
            }
            @Override
            public SettingMyChannelCreate createViewHolder(View view){
                return new SettingMyChannelCreate(
                    view,
                    (android.support.design.widget.TextInputLayout) view.findViewById(R.id.setting_my_channel_create__channel_name_layout),
                    (android.support.v7.widget.AppCompatEditText) view.findViewById(R.id.setting_my_channel_create__channel_name),
                    (android.support.design.widget.TextInputLayout) view.findViewById(R.id.setting_my_channel_create__channel_description_layout),
                    (android.support.v7.widget.AppCompatEditText) view.findViewById(R.id.setting_my_channel_create__channel_description)
                );
            }
        };
    }
}
