
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.CheckBox;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingSourceCopyRowItem;

public class SettingSourceCopyRowItemProvider implements ViewHolderProvider<SettingSourceCopyRowItem> {

    private final LayoutInflater inflater;

    public SettingSourceCopyRowItemProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingSourceCopyRowItemProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_source_copy_row__item;
    }

    @Override
    public SettingSourceCopyRowItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingSourceCopyRowItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_source_copy_row__item, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingSourceCopyRowItem> factory(){
        return new ViewHolderProviderFactory<SettingSourceCopyRowItem>() {
            @Override
            public ViewHolderProvider<SettingSourceCopyRowItem> create(LayoutInflater inflater){
                return new SettingSourceCopyRowItemProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingSourceCopyRowItem> create(Context context){
                return new SettingSourceCopyRowItemProvider(context);
            }
            @Override
            public SettingSourceCopyRowItem createViewHolder(View view){
                return new SettingSourceCopyRowItem(
                    view,
                    (CheckBox) view.findViewById(R.id.setting_source_copy_row__item__checked),
                    (TextView) view.findViewById(R.id.setting_source_copy_row__item__label)
                );
            }
        };
    }
}
