
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingPresetRow;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;

public class SettingPresetRowProvider implements ViewHolderProvider<SettingPresetRow> {

    private final LayoutInflater inflater;

    public SettingPresetRowProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingPresetRowProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_preset_row;
    }

    @Override
    public SettingPresetRow inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingPresetRow inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_preset_row, parent, attachToRoot);
        return new SettingPresetRow(
            view,
            (TextView) view.findViewById(R.id.setting_preset_row__name),
            (TextView) view.findViewById(R.id.setting_preset_row__description),
            (android.support.v7.widget.SwitchCompat) view.findViewById(R.id.setting_preset_row__switch_subscribe),
            (TextView) view.findViewById(R.id.setting_preset_row__sources)
        );
    }

    public static ViewHolderProviderFactory<SettingPresetRow> factory(){
        return new ViewHolderProviderFactory<SettingPresetRow>() {
            @Override
            public ViewHolderProvider<SettingPresetRow> create(LayoutInflater inflater){
                return new SettingPresetRowProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingPresetRow> create(Context context){
                return new SettingPresetRowProvider(context);
            }
        };
    }
}
