
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingMyChannelsLayout;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;

public class SettingMyChannelsLayoutProvider implements ViewHolderProvider<SettingMyChannelsLayout> {

    private final LayoutInflater inflater;

    public SettingMyChannelsLayoutProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingMyChannelsLayoutProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_my_channels_layout;
    }

    @Override
    public SettingMyChannelsLayout inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingMyChannelsLayout inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_my_channels_layout, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingMyChannelsLayout> factory(){
        return new ViewHolderProviderFactory<SettingMyChannelsLayout>() {
            @Override
            public ViewHolderProvider<SettingMyChannelsLayout> create(LayoutInflater inflater){
                return new SettingMyChannelsLayoutProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingMyChannelsLayout> create(Context context){
                return new SettingMyChannelsLayoutProvider(context);
            }
            @Override
            public SettingMyChannelsLayout createViewHolder(View view){
                return new SettingMyChannelsLayout(
                    view,
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.setting_my_channels_layout__toolbar),
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.setting_my_channels_layout__channel_list)
                );
            }
        };
    }
}
