
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingChannelOrderRowItem;

public class SettingChannelOrderRowItemProvider implements ViewHolderProvider<SettingChannelOrderRowItem> {

    private final LayoutInflater inflater;

    public SettingChannelOrderRowItemProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingChannelOrderRowItemProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_channel_order_row__item;
    }

    @Override
    public SettingChannelOrderRowItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingChannelOrderRowItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_channel_order_row__item, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public SettingChannelOrderRowItem inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<SettingChannelOrderRowItem> factory(){
        return new ViewHolderProviderFactory<SettingChannelOrderRowItem>() {
            @Override
            public ViewHolderProvider<SettingChannelOrderRowItem> create(LayoutInflater inflater){
                return new SettingChannelOrderRowItemProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingChannelOrderRowItem> create(Context context){
                return new SettingChannelOrderRowItemProvider(context);
            }
            @Override
            public SettingChannelOrderRowItem createViewHolder(View view){
                return new SettingChannelOrderRowItem(
                    view,
                    (ImageView) view.findViewById(R.id.setting_channel_order_row__item__start_dragging_left),
                    (ImageView) view.findViewById(R.id.setting_channel_order_row__item__start_dragging_right),
                    (TextView) view.findViewById(R.id.setting_channel_order_row__item__name)
                );
            }
        };
    }
}
