
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import android.support.v7.widget.SwitchCompat;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingMyChannelRow;

public class SettingMyChannelRowProvider implements ViewHolderProvider<SettingMyChannelRow> {

    private final LayoutInflater inflater;

    public SettingMyChannelRowProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingMyChannelRowProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_my_channel_row;
    }

    @Override
    public SettingMyChannelRow inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingMyChannelRow inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_my_channel_row, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingMyChannelRow> factory(){
        return new ViewHolderProviderFactory<SettingMyChannelRow>() {
            @Override
            public ViewHolderProvider<SettingMyChannelRow> create(LayoutInflater inflater){
                return new SettingMyChannelRowProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingMyChannelRow> create(Context context){
                return new SettingMyChannelRowProvider(context);
            }
            @Override
            public SettingMyChannelRow createViewHolder(View view){
                return new SettingMyChannelRow(
                    view,
                    (TextView) view.findViewById(R.id.setting_my_channel_row__name),
                    (TextView) view.findViewById(R.id.setting_my_channel_row__description),
                    (android.support.v7.widget.SwitchCompat) view.findViewById(R.id.setting_my_channel_row__switch_subscribe),
                    (TextView) view.findViewById(R.id.setting_my_channel_row__edit),
                    (TextView) view.findViewById(R.id.setting_my_channel_row__sources)
                );
            }
        };
    }
}
