
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingMyChannelRowFooter;

public class SettingMyChannelRowFooterProvider implements ViewHolderProvider<SettingMyChannelRowFooter> {

    private final LayoutInflater inflater;

    public SettingMyChannelRowFooterProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingMyChannelRowFooterProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_my_channel_row__footer;
    }

    @Override
    public SettingMyChannelRowFooter inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingMyChannelRowFooter inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_my_channel_row__footer, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public SettingMyChannelRowFooter inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<SettingMyChannelRowFooter> factory(){
        return new ViewHolderProviderFactory<SettingMyChannelRowFooter>() {
            @Override
            public ViewHolderProvider<SettingMyChannelRowFooter> create(LayoutInflater inflater){
                return new SettingMyChannelRowFooterProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingMyChannelRowFooter> create(Context context){
                return new SettingMyChannelRowFooterProvider(context);
            }
            @Override
            public SettingMyChannelRowFooter createViewHolder(View view){
                return new SettingMyChannelRowFooter(
                    view
                );
            }
        };
    }
}
