
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.v7.widget.Toolbar;
import android.support.v7.widget.RecyclerView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingChannelOrderLayout;

public class SettingChannelOrderLayoutProvider implements ViewHolderProvider<SettingChannelOrderLayout> {

    private final LayoutInflater inflater;

    public SettingChannelOrderLayoutProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingChannelOrderLayoutProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_channel_order_layout;
    }

    @Override
    public SettingChannelOrderLayout inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingChannelOrderLayout inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_channel_order_layout, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingChannelOrderLayout> factory(){
        return new ViewHolderProviderFactory<SettingChannelOrderLayout>() {
            @Override
            public ViewHolderProvider<SettingChannelOrderLayout> create(LayoutInflater inflater){
                return new SettingChannelOrderLayoutProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingChannelOrderLayout> create(Context context){
                return new SettingChannelOrderLayoutProvider(context);
            }
            @Override
            public SettingChannelOrderLayout createViewHolder(View view){
                return new SettingChannelOrderLayout(
                    view,
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.setting_channel_order_layout__toolbar),
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.setting_channel_order_layout__channel_list)
                );
            }
        };
    }
}
