
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import android.widget.ImageButton;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.SwitchCompat;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SettingScheduleRowItem;

public class SettingScheduleRowItemProvider implements ViewHolderProvider<SettingScheduleRowItem> {

    private final LayoutInflater inflater;

    public SettingScheduleRowItemProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SettingScheduleRowItemProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.setting_schedule_row__item;
    }

    @Override
    public SettingScheduleRowItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SettingScheduleRowItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.setting_schedule_row__item, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SettingScheduleRowItem> factory(){
        return new ViewHolderProviderFactory<SettingScheduleRowItem>() {
            @Override
            public ViewHolderProvider<SettingScheduleRowItem> create(LayoutInflater inflater){
                return new SettingScheduleRowItemProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SettingScheduleRowItem> create(Context context){
                return new SettingScheduleRowItemProvider(context);
            }
            @Override
            public SettingScheduleRowItem createViewHolder(View view){
                return new SettingScheduleRowItem(
                    view,
                    (TextView) view.findViewById(R.id.setting_schedule_row__item__name),
                    (ImageButton) view.findViewById(R.id.setting_schedule_row__item__menu),
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.setting_schedule_row__item__time_ranges),
                    (android.support.v7.widget.SwitchCompat) view.findViewById(R.id.setting_schedule_row__item__enabled),
                    (TextView) view.findViewById(R.id.setting_schedule_row__item__history)
                );
            }
        };
    }
}
