
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SourceSearchRowSourceError;

public class SourceSearchRowSourceErrorProvider implements ViewHolderProvider<SourceSearchRowSourceError> {

    private final LayoutInflater inflater;

    public SourceSearchRowSourceErrorProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SourceSearchRowSourceErrorProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.source_search_row__source_error;
    }

    @Override
    public SourceSearchRowSourceError inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SourceSearchRowSourceError inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.source_search_row__source_error, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SourceSearchRowSourceError> factory(){
        return new ViewHolderProviderFactory<SourceSearchRowSourceError>() {
            @Override
            public ViewHolderProvider<SourceSearchRowSourceError> create(LayoutInflater inflater){
                return new SourceSearchRowSourceErrorProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SourceSearchRowSourceError> create(Context context){
                return new SourceSearchRowSourceErrorProvider(context);
            }
            @Override
            public SourceSearchRowSourceError createViewHolder(View view){
                return new SourceSearchRowSourceError(
                    view,
                    (TextView) view.findViewById(R.id.source_search_row__source_error__message),
                    (TextView) view.findViewById(R.id.source_search_row__source_error__url),
                    (TextView) view.findViewById(R.id.source_search_row__source_error__retry)
                );
            }
        };
    }
}
