
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SourceSearchRowLabel;

public class SourceSearchRowLabelProvider implements ViewHolderProvider<SourceSearchRowLabel> {

    private final LayoutInflater inflater;

    public SourceSearchRowLabelProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SourceSearchRowLabelProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.source_search_row__label;
    }

    @Override
    public SourceSearchRowLabel inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SourceSearchRowLabel inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.source_search_row__label, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SourceSearchRowLabel> factory(){
        return new ViewHolderProviderFactory<SourceSearchRowLabel>() {
            @Override
            public ViewHolderProvider<SourceSearchRowLabel> create(LayoutInflater inflater){
                return new SourceSearchRowLabelProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SourceSearchRowLabel> create(Context context){
                return new SourceSearchRowLabelProvider(context);
            }
            @Override
            public SourceSearchRowLabel createViewHolder(View view){
                return new SourceSearchRowLabel(
                    view,
                    (TextView) view.findViewById(R.id.source_search_row__label__message),
                    (TextView) view.findViewById(R.id.source_search_row__label__date)
                );
            }
        };
    }
}
