
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SourceSearchRowLoadingErrorItem;

public class SourceSearchRowLoadingErrorItemProvider implements ViewHolderProvider<SourceSearchRowLoadingErrorItem> {

    private final LayoutInflater inflater;

    public SourceSearchRowLoadingErrorItemProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SourceSearchRowLoadingErrorItemProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.source_search_row__loading_error_item;
    }

    @Override
    public SourceSearchRowLoadingErrorItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SourceSearchRowLoadingErrorItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.source_search_row__loading_error_item, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SourceSearchRowLoadingErrorItem> factory(){
        return new ViewHolderProviderFactory<SourceSearchRowLoadingErrorItem>() {
            @Override
            public ViewHolderProvider<SourceSearchRowLoadingErrorItem> create(LayoutInflater inflater){
                return new SourceSearchRowLoadingErrorItemProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SourceSearchRowLoadingErrorItem> create(Context context){
                return new SourceSearchRowLoadingErrorItemProvider(context);
            }
            @Override
            public SourceSearchRowLoadingErrorItem createViewHolder(View view){
                return new SourceSearchRowLoadingErrorItem(
                    view,
                    (TextView) view.findViewById(R.id.source_search_row__loading_error_item__url),
                    (TextView) view.findViewById(R.id.source_search_row__loading_error_item__message),
                    (TextView) view.findViewById(R.id.source_search_row__loading_error_item__open)
                );
            }
        };
    }
}
