
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SourceSearchRowOriginError;

public class SourceSearchRowOriginErrorProvider implements ViewHolderProvider<SourceSearchRowOriginError> {

    private final LayoutInflater inflater;

    public SourceSearchRowOriginErrorProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SourceSearchRowOriginErrorProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.source_search_row__origin_error;
    }

    @Override
    public SourceSearchRowOriginError inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SourceSearchRowOriginError inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.source_search_row__origin_error, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public SourceSearchRowOriginError inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<SourceSearchRowOriginError> factory(){
        return new ViewHolderProviderFactory<SourceSearchRowOriginError>() {
            @Override
            public ViewHolderProvider<SourceSearchRowOriginError> create(LayoutInflater inflater){
                return new SourceSearchRowOriginErrorProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SourceSearchRowOriginError> create(Context context){
                return new SourceSearchRowOriginErrorProvider(context);
            }
            @Override
            public SourceSearchRowOriginError createViewHolder(View view){
                return new SourceSearchRowOriginError(
                    view,
                    (TextView) view.findViewById(R.id.source_search_row__origin_error__message),
                    (TextView) view.findViewById(R.id.source_search_row__origin_error__url)
                );
            }
        };
    }
}
