
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SourceSearchRowClientError;

public class SourceSearchRowClientErrorProvider implements ViewHolderProvider<SourceSearchRowClientError> {

    private final LayoutInflater inflater;

    public SourceSearchRowClientErrorProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SourceSearchRowClientErrorProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.source_search_row__client_error;
    }

    @Override
    public SourceSearchRowClientError inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SourceSearchRowClientError inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.source_search_row__client_error, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SourceSearchRowClientError> factory(){
        return new ViewHolderProviderFactory<SourceSearchRowClientError>() {
            @Override
            public ViewHolderProvider<SourceSearchRowClientError> create(LayoutInflater inflater){
                return new SourceSearchRowClientErrorProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SourceSearchRowClientError> create(Context context){
                return new SourceSearchRowClientErrorProvider(context);
            }
            @Override
            public SourceSearchRowClientError createViewHolder(View view){
                return new SourceSearchRowClientError(
                    view,
                    (TextView) view.findViewById(R.id.source_search_row__client_error__message),
                    (TextView) view.findViewById(R.id.source_search_row__client_error__url),
                    (TextView) view.findViewById(R.id.source_search_row__client_error__retry)
                );
            }
        };
    }
}
