
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SourceSearchRowSourceLabel;

public class SourceSearchRowSourceLabelProvider implements ViewHolderProvider<SourceSearchRowSourceLabel> {

    private final LayoutInflater inflater;

    public SourceSearchRowSourceLabelProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SourceSearchRowSourceLabelProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.source_search_row__source_label;
    }

    @Override
    public SourceSearchRowSourceLabel inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SourceSearchRowSourceLabel inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.source_search_row__source_label, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<SourceSearchRowSourceLabel> factory(){
        return new ViewHolderProviderFactory<SourceSearchRowSourceLabel>() {
            @Override
            public ViewHolderProvider<SourceSearchRowSourceLabel> create(LayoutInflater inflater){
                return new SourceSearchRowSourceLabelProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SourceSearchRowSourceLabel> create(Context context){
                return new SourceSearchRowSourceLabelProvider(context);
            }
            @Override
            public SourceSearchRowSourceLabel createViewHolder(View view){
                return new SourceSearchRowSourceLabel(
                    view,
                    (TextView) view.findViewById(R.id.source_search_row__source_label__body)
                );
            }
        };
    }
}
