
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.design.widget.TextInputLayout;
import android.support.v7.widget.AppCompatEditText;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SourceSearchStart;

public class SourceSearchStartProvider implements ViewHolderProvider<SourceSearchStart> {

    private final LayoutInflater inflater;

    public SourceSearchStartProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SourceSearchStartProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.source_search_start;
    }

    @Override
    public SourceSearchStart inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SourceSearchStart inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.source_search_start, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public SourceSearchStart inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<SourceSearchStart> factory(){
        return new ViewHolderProviderFactory<SourceSearchStart>() {
            @Override
            public ViewHolderProvider<SourceSearchStart> create(LayoutInflater inflater){
                return new SourceSearchStartProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SourceSearchStart> create(Context context){
                return new SourceSearchStartProvider(context);
            }
            @Override
            public SourceSearchStart createViewHolder(View view){
                return new SourceSearchStart(
                    view,
                    (android.support.design.widget.TextInputLayout) view.findViewById(R.id.source_search_start__origin_url_layout),
                    (android.support.v7.widget.AppCompatEditText) view.findViewById(R.id.source_search_start__origin_url)
                );
            }
        };
    }
}
