
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.v7.widget.RecyclerView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.SubscribeSourceLayout;

public class SubscribeSourceLayoutProvider implements ViewHolderProvider<SubscribeSourceLayout> {

    private final LayoutInflater inflater;

    public SubscribeSourceLayoutProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public SubscribeSourceLayoutProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.subscribe_source_layout;
    }

    @Override
    public SubscribeSourceLayout inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public SubscribeSourceLayout inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.subscribe_source_layout, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public SubscribeSourceLayout inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<SubscribeSourceLayout> factory(){
        return new ViewHolderProviderFactory<SubscribeSourceLayout>() {
            @Override
            public ViewHolderProvider<SubscribeSourceLayout> create(LayoutInflater inflater){
                return new SubscribeSourceLayoutProvider(inflater);
            }
            @Override
            public ViewHolderProvider<SubscribeSourceLayout> create(Context context){
                return new SubscribeSourceLayoutProvider(context);
            }
            @Override
            public SubscribeSourceLayout createViewHolder(View view){
                return new SubscribeSourceLayout(
                    view,
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.subscribe_source_layout__channels)
                );
            }
        };
    }
}
