
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadSourceRowItem;

public class UnreadSourceRowItemProvider implements ViewHolderProvider<UnreadSourceRowItem> {

    private final LayoutInflater inflater;

    public UnreadSourceRowItemProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public UnreadSourceRowItemProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.unread_source_row__item;
    }

    @Override
    public UnreadSourceRowItem inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadSourceRowItem inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_source_row__item, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public UnreadSourceRowItem inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<UnreadSourceRowItem> factory(){
        return new ViewHolderProviderFactory<UnreadSourceRowItem>() {
            @Override
            public ViewHolderProvider<UnreadSourceRowItem> create(LayoutInflater inflater){
                return new UnreadSourceRowItemProvider(inflater);
            }
            @Override
            public ViewHolderProvider<UnreadSourceRowItem> create(Context context){
                return new UnreadSourceRowItemProvider(context);
            }
            @Override
            public UnreadSourceRowItem createViewHolder(View view){
                return new UnreadSourceRowItem(
                    view,
                    (TextView) view.findViewById(R.id.unread_source_row__item__title),
                    (TextView) view.findViewById(R.id.unread_source_row__item__description)
                );
            }
        };
    }
}
