
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.ProgressBar;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadSourceRowFooter;

public class UnreadSourceRowFooterProvider implements ViewHolderProvider<UnreadSourceRowFooter> {

    private final LayoutInflater inflater;

    public UnreadSourceRowFooterProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public UnreadSourceRowFooterProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.unread_source_row__footer;
    }

    @Override
    public UnreadSourceRowFooter inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadSourceRowFooter inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_source_row__footer, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    public static ViewHolderProviderFactory<UnreadSourceRowFooter> factory(){
        return new ViewHolderProviderFactory<UnreadSourceRowFooter>() {
            @Override
            public ViewHolderProvider<UnreadSourceRowFooter> create(LayoutInflater inflater){
                return new UnreadSourceRowFooterProvider(inflater);
            }
            @Override
            public ViewHolderProvider<UnreadSourceRowFooter> create(Context context){
                return new UnreadSourceRowFooterProvider(context);
            }
            @Override
            public UnreadSourceRowFooter createViewHolder(View view){
                return new UnreadSourceRowFooter(
                    view,
                    (ProgressBar) view.findViewById(R.id.tools_progress_indeterminate_h__progress_bar)
                );
            }
        };
    }
}
