
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadDetailRowEntry;

public class UnreadDetailRowEntryProvider implements ViewHolderProvider<UnreadDetailRowEntry> {

    private final LayoutInflater inflater;

    public UnreadDetailRowEntryProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public UnreadDetailRowEntryProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.unread_detail_row__entry;
    }

    @Override
    public UnreadDetailRowEntry inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadDetailRowEntry inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_detail_row__entry, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public UnreadDetailRowEntry inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<UnreadDetailRowEntry> factory(){
        return new ViewHolderProviderFactory<UnreadDetailRowEntry>() {
            @Override
            public ViewHolderProvider<UnreadDetailRowEntry> create(LayoutInflater inflater){
                return new UnreadDetailRowEntryProvider(inflater);
            }
            @Override
            public ViewHolderProvider<UnreadDetailRowEntry> create(Context context){
                return new UnreadDetailRowEntryProvider(context);
            }
            @Override
            public UnreadDetailRowEntry createViewHolder(View view){
                return new UnreadDetailRowEntry(
                    view,
                    (TextView) view.findViewById(R.id.unread_detail_row__entry__title),
                    (TextView) view.findViewById(R.id.unread_detail_row__entry__content),
                    (TextView) view.findViewById(R.id.unread_detail_row__entry__later),
                    (TextView) view.findViewById(R.id.unread_detail_row__entry__visit)
                );
            }
        };
    }
}
