
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadOutlineRowSource;

public class UnreadOutlineRowSourceProvider implements ViewHolderProvider<UnreadOutlineRowSource> {

    private final LayoutInflater inflater;

    public UnreadOutlineRowSourceProvider(Context context){
        inflater = LayoutInflater.from(context);
    }

    @Override
    public int layoutId(){
        return R.layout.unread_outline_row__source;
    }

    @Override
    public UnreadOutlineRowSource inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadOutlineRowSource inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_outline_row__source, parent, attachToRoot);
        return new UnreadOutlineRowSource(
            view,
            (TextView) view.findViewById(R.id.unread_outline_row__source__title)
        );
    }
}
