
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.ProgressBar;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadOutlineRowFooter;

public class UnreadOutlineRowFooterProvider implements ViewHolderProvider<UnreadOutlineRowFooter> {

    private final LayoutInflater inflater;

    public UnreadOutlineRowFooterProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public UnreadOutlineRowFooterProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.unread_outline_row__footer;
    }

    @Override
    public UnreadOutlineRowFooter inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadOutlineRowFooter inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_outline_row__footer, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public UnreadOutlineRowFooter inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<UnreadOutlineRowFooter> factory(){
        return new ViewHolderProviderFactory<UnreadOutlineRowFooter>() {
            @Override
            public ViewHolderProvider<UnreadOutlineRowFooter> create(LayoutInflater inflater){
                return new UnreadOutlineRowFooterProvider(inflater);
            }
            @Override
            public ViewHolderProvider<UnreadOutlineRowFooter> create(Context context){
                return new UnreadOutlineRowFooterProvider(context);
            }
            @Override
            public UnreadOutlineRowFooter createViewHolder(View view){
                return new UnreadOutlineRowFooter(
                    view,
                    (ProgressBar) view.findViewById(R.id._tools_progress_indeterminate_h__progress_bar)
                );
            }
        };
    }
}
