
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.support.v4.widget.DrawerLayout;
import android.widget.LinearLayout;
import android.support.v7.widget.RecyclerView;
import android.widget.RelativeLayout;
import android.support.v7.widget.Toolbar;
import android.support.design.widget.FloatingActionButton;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadItemsLayout;

public class UnreadItemsLayoutProvider implements ViewHolderProvider<UnreadItemsLayout> {

    private final LayoutInflater inflater;

    public UnreadItemsLayoutProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public UnreadItemsLayoutProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.unread_items_layout;
    }

    @Override
    public UnreadItemsLayout inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadItemsLayout inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_items_layout, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public UnreadItemsLayout inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<UnreadItemsLayout> factory(){
        return new ViewHolderProviderFactory<UnreadItemsLayout>() {
            @Override
            public ViewHolderProvider<UnreadItemsLayout> create(LayoutInflater inflater){
                return new UnreadItemsLayoutProvider(inflater);
            }
            @Override
            public ViewHolderProvider<UnreadItemsLayout> create(Context context){
                return new UnreadItemsLayoutProvider(context);
            }
            @Override
            public UnreadItemsLayout createViewHolder(View view){
                return new UnreadItemsLayout(
                    view,
                    (android.support.v4.widget.DrawerLayout) view.findViewById(R.id.unread_items_layout__drawer_menu),
                    (LinearLayout) view.findViewById(R.id.unread_items_layout__menu_area),
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.unread_items_layout__menu_list),
                    (LinearLayout) view.findViewById(R.id.unread_items_panes__pane_container),
                    (RelativeLayout) view.findViewById(R.id.unread_items_panes__source_area),
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.unread_items_panes__source_toolbar),
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.unread_items_panes__source_list),
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.unread_items_panes__source_bottom_bar),
                    (android.support.design.widget.FloatingActionButton) view.findViewById(R.id.unread_items_panes__source_to_next),
                    (RelativeLayout) view.findViewById(R.id.unread_items_panes__entry_area),
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.unread_items_panes__entry_toolbar),
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.unread_items_panes__entry_list),
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.unread_items_panes__entry_bottom_bar),
                    (android.support.design.widget.FloatingActionButton) view.findViewById(R.id.unread_items_panes__entry_to_next),
                    (RelativeLayout) view.findViewById(R.id.unread_items_panes__entry_detail_area),
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.unread_items_panes__entry_detail_toolbar),
                    (android.support.v7.widget.RecyclerView) view.findViewById(R.id.unread_items_panes__entry_detail_list),
                    (android.support.v7.widget.Toolbar) view.findViewById(R.id.unread_items_panes__detail_bottom_bar),
                    (android.support.design.widget.FloatingActionButton) view.findViewById(R.id.unread_items_panes__detail_to_next)
                );
            }
        };
    }
}
