
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.wheat.ancient.resource.ViewHolderProviderFactory;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadDetailRowSource;

public class UnreadDetailRowSourceProvider implements ViewHolderProvider<UnreadDetailRowSource> {

    private final LayoutInflater inflater;

    public UnreadDetailRowSourceProvider(Context context){
        this.inflater = LayoutInflater.from(context);
    }

    public UnreadDetailRowSourceProvider(LayoutInflater inflater){
        this.inflater = inflater;
    }

    @Override
    public int layoutId(){
        return R.layout.unread_detail_row__source;
    }

    @Override
    public UnreadDetailRowSource inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadDetailRowSource inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_detail_row__source, parent, attachToRoot);
        return factory().createViewHolder(view);
    }

    @Override
    public UnreadDetailRowSource inflate(){
        return inflate(null, false);
    }

    public static ViewHolderProviderFactory<UnreadDetailRowSource> factory(){
        return new ViewHolderProviderFactory<UnreadDetailRowSource>() {
            @Override
            public ViewHolderProvider<UnreadDetailRowSource> create(LayoutInflater inflater){
                return new UnreadDetailRowSourceProvider(inflater);
            }
            @Override
            public ViewHolderProvider<UnreadDetailRowSource> create(Context context){
                return new UnreadDetailRowSourceProvider(context);
            }
            @Override
            public UnreadDetailRowSource createViewHolder(View view){
                return new UnreadDetailRowSource(
                    view,
                    (TextView) view.findViewById(R.id.unread_detail_row__source__title)
                );
            }
        };
    }
}
