
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadSourceRow;

public class UnreadSourceRowProvider implements ViewHolderProvider<UnreadSourceRow> {

    private final LayoutInflater inflater;

    public UnreadSourceRowProvider(Context context){
        inflater = LayoutInflater.from(context);
    }

    @Override
    public int layoutId(){
        return R.layout.unread_source_row;
    }

    @Override
    public UnreadSourceRow inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadSourceRow inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_source_row, parent, attachToRoot);
        return new UnreadSourceRow(
            view,
            (TextView) view.findViewById(R.id.unread_source_row__title),
            (TextView) view.findViewById(R.id.unread_source_row__description)
        );
    }
}
