
/**
 * This file is automatically generated by wheat-build.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.linen.res.layout;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.view.View;
import android.widget.TextView;
import x7c1.wheat.ancient.resource.ViewHolderProvider;
import x7c1.linen.R;
import x7c1.linen.glue.res.layout.UnreadOutlineRow;

public class UnreadOutlineRowProvider implements ViewHolderProvider<UnreadOutlineRow> {

    private final LayoutInflater inflater;

    public UnreadOutlineRowProvider(Context context){
        inflater = LayoutInflater.from(context);
    }

    @Override
    public int layoutId(){
        return R.layout.unread_outline_row;
    }

    @Override
    public UnreadOutlineRow inflateOn(ViewGroup parent){
        return inflate(parent, false);
    }

    @Override
    public UnreadOutlineRow inflate(ViewGroup parent, boolean attachToRoot){
        View view = inflater.inflate(R.layout.unread_outline_row, parent, attachToRoot);
        return new UnreadOutlineRow(
            view,
            (TextView) view.findViewById(R.id.unread_outline_row__title)
        );
    }
}
